import type { CaptureViewport } from '../interfaces/capture-result.interface.js';

export interface CapturedRect {
  x: number;
  y: number;
  width: number;
  height: number;
  top: number;
  left: number;
  right: number;
  bottom: number;
}

export interface CapturedStyles {
  display: string;
  position: string;
  width: string;
  height: string;
  minWidth: string;
  minHeight: string;
  maxWidth: string;
  maxHeight: string;
  margin: string;
  padding: string;
  color: string;
  background: string;
  backgroundColor: string;
  fontFamily: string;
  fontSize: string;
  fontWeight: string;
  fontStyle: string;
  lineHeight: string;
  letterSpacing: string;
  textAlign: string;
  textDecoration: string;
  border: string;
  borderRadius: string;
  boxShadow: string;
  opacity: string;
  overflow: string;
  flexDirection: string;
  flexWrap: string;
  alignItems: string;
  justifyContent: string;
  gap: string;
  gridTemplateColumns: string;
  gridTemplateRows: string;
  transform: string;
  zIndex: string;
}

export type CapturedAssetKind = 'img' | 'source' | 'background-image' | 'svg';

export interface CapturedAsset {
  kind: CapturedAssetKind;
  url: string;
  /** Id of the {@link CapturedNode} this asset was found on. */
  nodeId: string;
  srcset?: string;
}

export interface CapturedNode {
  /** Id generated by Doppelganger during extraction, unique within a single capture. */
  id: string;
  tag: string;
  /** Text directly owned by this element, excluding text from descendant elements. */
  text: string | null;
  attributes: Record<string, string>;
  rect: CapturedRect;
  styles: CapturedStyles;
  children: CapturedNode[];
}

export interface CapturedPage {
  url: string;
  title: string;
  viewport: CaptureViewport;
  /** Root of the captured tree, rooted at `<body>`. Null when the page has no body. */
  root: CapturedNode | null;
  assets: CapturedAsset[];
  /** Number of nodes included in `root` (ignored tags are not counted). */
  nodeCount: number;
}
