import type { CaptureViewport } from '../interfaces/capture-result.interface.js';

export interface CapturedRect {
  x: number;
  y: number;
  width: number;
  height: number;
  top: number;
  left: number;
  right: number;
  bottom: number;
}

export interface CapturedStyles {
  display: string;
  position: string;
  boxSizing: string;
  top: string;
  right: string;
  bottom: string;
  left: string;
  width: string;
  height: string;
  minWidth: string;
  minHeight: string;
  maxWidth: string;
  maxHeight: string;
  margin: string;
  padding: string;
  color: string;
  background: string;
  backgroundColor: string;
  fontFamily: string;
  fontSize: string;
  fontWeight: string;
  fontStyle: string;
  lineHeight: string;
  letterSpacing: string;
  textAlign: string;
  textDecoration: string;
  /**
   * Per-side, not the `border` shorthand: the shorthand's resolved value is
   * only defined when all four sides are identical (CSSOM), so it comes back
   * as an empty string for the extremely common border-bottom-only pattern
   * (table rows, dividers) — silently dropping the border on reconstruction.
   */
  borderTop: string;
  borderRight: string;
  borderBottom: string;
  borderLeft: string;
  borderRadius: string;
  boxShadow: string;
  opacity: string;
  overflow: string;
  listStyle: string;
  flexDirection: string;
  flexWrap: string;
  alignItems: string;
  justifyContent: string;
  gap: string;
  gridTemplateColumns: string;
  gridTemplateRows: string;
  transform: string;
  zIndex: string;
}

export type CapturedAssetKind = 'img' | 'source' | 'background-image' | 'svg';

export interface CapturedAsset {
  kind: CapturedAssetKind;
  url: string;
  /** Id of the {@link CapturedElementNode} this asset was found on. */
  nodeId: string;
  srcset?: string;
}

/**
 * A DOM text node. Kept as its own node (rather than folded into a `text`
 * field on the parent element) so that its position among its element
 * siblings is preserved exactly as it was in the source DOM.
 */
export interface CapturedTextNode {
  kind: 'text';
  /** Id generated by Doppelganger during extraction, unique within a single capture. */
  id: string;
  /** Whitespace-normalized text (consecutive whitespace collapsed to a single space). */
  text: string;
}

export interface CapturedElementNode {
  kind: 'element';
  /** Id generated by Doppelganger during extraction, unique within a single capture. */
  id: string;
  tag: string;
  attributes: Record<string, string>;
  rect: CapturedRect;
  styles: CapturedStyles;
  /** Element and text children, in exact DOM order. */
  children: CapturedNode[];
}

/** A node in the captured tree: either an element or a text run. */
export type CapturedNode = CapturedElementNode | CapturedTextNode;

export interface CapturedPage {
  url: string;
  title: string;
  viewport: CaptureViewport;
  /** Root of the captured tree, rooted at `<body>`. Null when the page has no body. */
  root: CapturedElementNode | null;
  assets: CapturedAsset[];
  /** Number of nodes (elements and text) included in `root`. */
  nodeCount: number;
}
