import type { CaptureViewport } from '../interfaces/capture-result.interface.js';

export interface CapturedRect {
  x: number;
  y: number;
  width: number;
  height: number;
  top: number;
  left: number;
  right: number;
  bottom: number;
}

/**
 * Every enumerable computed CSS property Chromium reports for an element
 * (via `getComputedStyle(element).item(i)`/`getPropertyValue()`), keyed by
 * its real kebab-case CSS name (`"background-color"`, `"grid-column-start"`,
 * `"--brand-color"`...) — not a hand-picked allowlist. This includes CSS
 * custom properties (`--foo`).
 *
 * Why not a curated list of ~40 properties (the pre-Milestone-5 design):
 * real-world pages use hundreds of longhand properties for layout (grid
 * placement, flex sizing, logical properties, etc.), and maintaining a
 * manual list meant every missing property was a silent, hard-to-diagnose
 * visual bug (see the Milestone 2.5/4 write-ups — box-sizing, per-side
 * border, position offsets and list-style were each found this way, one at
 * a time). Capturing everything the browser already computed removes that
 * entire failure mode. Shorthands (e.g. `margin`, `border`, `grid-column`)
 * are intentionally NOT captured as such: Chromium's indexed enumeration
 * only exposes true longhands, but every shorthand decomposes losslessly
 * into the longhands that back it, so nothing is lost — a renderer emitting
 * `margin-top`/`margin-right`/`margin-bottom`/`margin-left` individually
 * produces an identical box to one shorthand `margin` declaration.
 */
export type CapturedStyles = Record<string, string>;

/**
 * `::before`/`::after`/`::marker` captured only when they render something
 * (see dom-extractor.browser.ts for the exact "is this meaningful" check).
 * `styles` already contains the pseudo-element's `content` value alongside
 * everything else — there's no separate `content` field, since it's just
 * one more entry in the same computed-style record used for real elements.
 */
export interface CapturedPseudoElement {
  kind: 'before' | 'after' | 'marker';
  styles: CapturedStyles;
}

export type CapturedAssetKind = 'img' | 'source' | 'background-image' | 'svg';

export interface CapturedAsset {
  kind: CapturedAssetKind;
  url: string;
  /** Id of the {@link CapturedElementNode} this asset was found on. */
  nodeId: string;
  srcset?: string;
}

/**
 * A DOM text node. Kept as its own node (rather than folded into a `text`
 * field on the parent element) so that its position among its element
 * siblings is preserved exactly as it was in the source DOM.
 */
export interface CapturedTextNode {
  kind: 'text';
  /** Id generated by Doppelganger during extraction, unique within a single capture. */
  id: string;
  /** Whitespace-normalized text (consecutive whitespace collapsed to a single space). */
  text: string;
}

export interface CapturedElementNode {
  kind: 'element';
  /** Id generated by Doppelganger during extraction, unique within a single capture. */
  id: string;
  tag: string;
  attributes: Record<string, string>;
  rect: CapturedRect;
  styles: CapturedStyles;
  /** ::before/::after/::marker, only present when at least one renders something. */
  pseudoElements?: CapturedPseudoElement[];
  /** Element and text children, in exact DOM order. */
  children: CapturedNode[];
}

/** A node in the captured tree: either an element or a text run. */
export type CapturedNode = CapturedElementNode | CapturedTextNode;

export interface CapturedPage {
  url: string;
  title: string;
  viewport: CaptureViewport;
  /** Root of the captured tree, rooted at `<body>`. Null when the page has no body. */
  root: CapturedElementNode | null;
  assets: CapturedAsset[];
  /** Number of nodes (elements and text) included in `root`. */
  nodeCount: number;
}
